### ISSUE TITLE
Switching from Rye to UV: Dependency Compatibility Issue

### ISSUE THREAD

**Issue by rutkovskii** [HansBambel/SmaAt-UNet#37]
I attempted to switch from Rye to UV by modifying `[tool.rye]` and `[[tool.rye.sources]]` to `[tool.uv]` and `[[tool.uv.sources]]` in `pyproject.toml`. However, I encountered issues due to the dependencies specified in `pyproject.toml` with `requires-python = ">=3.10"`, specifically:

```toml
dependencies = [
    "tqdm~=4.65.0",
    "torch==2.2.2+cu121",
    "torchvision>=0.15.1",
    "torchsummary>=1.5.1",
    "h5py~=3.8.0",
    "fastapi~=0.80",
    "lightning~=2.2.1",
    "tensorboard~=2.13.0",
    "pandas~=1.5.3",
    "tables>=3.9.2",
    "matplotlib>=3.8.3",
]
```

Currently, I have copied the relevant parts of `pyproject.toml` (starting from line 40) and attempted to install the dependencies using:

`uv add <dependencies without specified versions>`

Would you be okay with updating the dependencies to versions compatible with UV instead of strictly using those from Rye?

**Comment by rutkovskii** [comment]
These are the versions now, but list is smaller, because I used dependencies listed in `README.md`:

```toml
[project]
name = "smaat-unet"
version = "0.1.0"
description = "Code for the paper `SmaAt-UNet: Precipitation Nowcasting using a Small Attention-UNet Architecture`"
authors = [{ name = "Kevin Trebing", email = "Kevin.Trebing@gmx.net" }]
readme = "README.md"
requires-python = ">=3.10.11"
dependencies = [
    "h5py>=3.12.1",
    "lightning>=2.5.0.post0",
    "numpy>=2.2.3",
    "tensorboard>=2.19.0",
    "torch>=2.6.0",
    "torchsummary>=1.5.1",
    "tqdm>=4.67.1",
]
```
